index:
    path: /
    controller: App\Controller\DefaultController::index

homepage:
    path: /
    controller: App\Controller\DefaultController::index

car:
    path: /car
    controller: App\Controller\DefaultController::index
